### ISSUE TITLE
Add support for findBySinceUpdate using since_update in metadata

### ISSUE THREAD

**Issue by qihaiyan** [aerospike/spring-data-aerospike#631]

**Comment by agrgr** [comment]
Hi @qihaiyan!

In your use case do you need querying only by SINCE_UPDATE (not combined query)?
Do you require repository level API (like "findByMetadata()") or is it enough for your needs to use Qualifier level (e.g. like in QualifierTests)?

**Comment by qihaiyan** [comment]
Querying by SINCE_UPDATE and combined query is better.
Metadata query doesn't need to read data from disk, so using metadata like SINCE_UPDATE will give us a better performance.
In my case, i need to find records changed in a period, querying by SINCE_UPDATE is more performance than qualifier level. @agrgr

**Comment by agrgr** [comment]
@qihaiyan Support for metadata querying will be added in the next release 4.6.0.
