### ISSUE TITLE
MappingAerospikeReadConverter can only handle Map bins with String key

### ISSUE THREAD

**Issue by mikhail-hul** [aerospike/spring-data-aerospike#670]
Version com.aerospike:spring-data-aerospike:4.3.0
`class java.lang.Long cannot be cast to class java.lang.String` ClassCastException at 
`org.springframework.data.aerospike.convertMappingAerospikeReadConverter.convertMap` as 
has method params defined as  `Map<String, Object> source, TypeInformation<?> propertyType`
which is causing the exception when attempting to call `source.forEach` method if source has Long as a key.

The data was loaded by non-spring client. 
com.aerospike:spring-data-aerospike:3.4.0 had no such issue

**Comment by roimenashe** [comment]
Hi @mikhail-hul,

Currently Spring Data Aerospike stores record keys and Map keys as Strings, on reads it converts the key to the original type that included in the POJO (class that annotated with @Document).
This was a legacy decision by the previous maintainers.

We are aware that it is not ideal and we already have a solution for that for the next release of Spring Data Aerospike (4.6.0) which we plan to release soon. The default behavior is still going to be a String but there will be an optional flag to store the keys as the original given type (in case this type is a supported key types of Aerospike database). Somewhere in the future that will be the default behavior.

**Comment by mikhail-hul** [comment]
Now I see that it's made by design, but due to the details of the implementation in _spring-data-aerospike_, the issue appeared only in 4.3.0. We used 3.4.0 for reading data and were writing with a bare Aerospike client and it was working fine. Now we are preparing to upgrade the Aerospike cluster and need to upgrade Aerospike clients to 6.1.x version. According to [compatibility matrix ](https://github.com/aerospike-community/spring-data-aerospike-starters#versions-compatibility-table) we need to upgrade _spring-data-aerospike_ to 3.5.0+. But this is blocked by this issue as we have a production dataset incompatible with the newer _spring-data-aerospike_ version.

**Comment by reugn** [comment]
@mikhail-hul, [v4.6.0](https://github.com/aerospike/spring-data-aerospike/releases/tag/4.6.0), which addresses your issue, is released. See the compatibility table for dependencies versions information.
