### ISSUE TITLE
Add `Instant` conversion to `AerospikeCustomConversion`

### ISSUE THREAD

**Issue by nickaden** [aerospike/spring-data-aerospike#788]
Hello. It's common usage of `Instant` in software development to record timestamp of event or any other date-coupled objects. We already have `LocalDateTime` converter, but using this object for storing timestamps is not convinient since you need to define timezone in which you will store your timestamp. 

So I suggest to add conversion for `Instant` as it was done for `LocalDateTime`

**Comment by agrgr** [comment]
Hello @nickaden,

Thanks for the contribution, indeed, it might be useful.
